version: '3.8'
services:
  server:
    container_name: hacker-news-backend
    restart: always
    build: hacker-news-backend/.
    ports:
      - '3789:3789'
    links:
      - mongo
  client:
    hostname: localhost
    container_name: hacker-news-frontend
    restart: always
    build: hacker-news-frontend/.
    ports:
      - '4200:4200'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'