version: '3.8'
services:
  server:
    container_name: backend
    restart: always
    build: backend/.
    ports:
      - '3789:3789'
    links:
      - mongo
  client:
    hostname: localhost
    container_name: frontend
    restart: always
    build: frontend/.
    ports:
      - '4200:4200'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'